### ISSUE TITLE
Type mismatch problem when trying to get annotation from returnType of method

### ISSUE THREAD

**Issue by dholzenburg** [google/j2objc#715] opened 2016-02-21 12:27 UTC
Hi,

I have a annotated Java class. Translation fails when using reflection on method.getReturnType().getAnnotation(...)
`error: /Users/bla/NetBeansProjects/j2objc-test/src/main/java/com/j2objc/test/annotation/SomeClass.java:18: Type mismatch: cannot convert from Annotation to SomeAnnotation`

Since the getAnnotation() call on the method suceeds I think this is "just" a bug, not a general problem, isn't it?

``` java
@SomeAnnotation
public class SomeClass {

    public void methodWithReflection() throws NoSuchMethodException {
        final Method method = this.getClass().getMethod("someMethod");

        //works
        final SomeAnnotation annotation1 = method.getAnnotation(SomeAnnotation.class);
        //does not work
        final SomeAnnotation annotation2 = method.getReturnType().getAnnotation(SomeAnnotation.class);
    }

    @SomeAnnotation
    public SomeClass someMethod() {
        return null;
    }
}
```

``` java
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface SomeAnnotation {

    String value() default "";
}
```

**Comment by tomball** [comment] 2016-02-21 17:55
Sounds like "just a bug" (we should add a project issue label for that:-),
since JUnit 4 tests wouldn't run if it totally didn't work. Your classes
look sufficient to duplicate the issue, but if you attach them to a new
issue you'll be notified as soon as it's fixed.

**Comment by dholzenburg** [comment] 2016-02-22 19:43
Hi Tom,

thank you for the fast response.

I'm not sure what you mean by "..., but if you attach them to a new
issue you'll be notified as soon as it's fixed.".

Is there anything I need to do? I am not that familiar with github yet...

**Comment by tomball** [comment] 2016-02-23 17:27
No worries. You can create a new j2objc issue here
<https://github.com/google/j2objc/issues/new>. If you have a GitHub account
(free, plus they don't sell your account details to evil marketers :-),
then as we update the report you'll get an email.

**Comment by dholzenburg** [comment] 2016-02-24 12:19
But why creating a new issue? This one is already an issue, isn't it?

**Comment by tomball** [comment] 2016-02-24 17:57
Doh! You're right, and I shouldn't respond to email while being a tour
guide for visiting relatives. :-)

**Comment by dholzenburg** [comment] 2016-02-25 22:06
:-)

**Comment by tomball** [comment] 2016-02-25 22:58
The problem is with the version of Eclipse compiler that j2objc uses for its front-end. Unfortunately, we can't upgrade to the current version (where it's fixed) at this time because that introduces other bugs.

A workaround is to add a cast:

    final SomeAnnotation annotation2 =
        (SomeAnnotation)method.getReturnType().getAnnotation(SomeAnnotation.class);

This will be fixed as soon as a Eclipse point release addresses those other problems.

**Comment by dholzenburg** [comment] 2016-02-26 10:30
Thank you very much for the explanation and the workaround. Let's keep this issue open until the new version of the Eclipse compiler is used.

**Comment by dholzenburg** [comment] 2018-04-17 10:47
Any updates on this one? 

Tried again yesterday with j2objc 2.0.5 and it still seems to be an issue. The suggested workaround is still needed and working.

**Comment by tomball** [comment] 2018-04-17 19:55
I can't duplicate this problem with your original test, here's my modifications so it builds with javac and has labels to make sure the correct annotation instance is returned.

SomeAnnotation.java:
```
import java.lang.annotation.*;

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface SomeAnnotation {
  String value() default "";
}
```

SomeClass.java:
```
import java.lang.reflect.*;

@SomeAnnotation("type")
public class SomeClass {

  public static void main(String... args) throws NoSuchMethodException {
    final Method method = SomeClass.class.getMethod("someMethod");

    System.out.println("annotation on method: " + method.getAnnotation(SomeAnnotation.class));
    System.out.println("annotation on return type: "
        + method.getReturnType().getAnnotation(SomeAnnotation.class));
  }

  @SomeAnnotation("method")
  public SomeClass someMethod() {
    return null;
  }
}
```
Here's the output, using an unzipped download of j2objc-2.0.5:
```
$ javac SomeClass.java SomeAnnotation.java
$ java SomeClass
annotation on method: @SomeAnnotation(value=method)
annotation on return type: @SomeAnnotation(value=type)
$ ~/Downloads/j2objc-2.0.5/j2objc SomeClass.java SomeAnnotation.java
$ ~/Downloads/j2objc-2.0.5/j2objcc SomeClass.m SomeAnnotation.m
$ ./a.out SomeClass
annotation on method: @SomeAnnotation(value=method)
annotation on return type: @SomeAnnotation(value=type)
```
I'm closing this bug since we switched j2objc's front-end to use javac, so an Eclipse bug like this is no longer relevant. If you have still have problems, please file a new bug with a test that works with javac and fails with j2objc.

**Closed by tomball** 2018-04-17 19:55 UTC
