### ISSUE TITLE
ParameterizedType.getActualTypeArguments()

### ISSUE THREAD

**Issue by chadlowe3** [google/j2objc#939] opened 2018-01-31 22:26 UTC
We just upgraded to the latest version of J2ObjC (from 1.0.2).

The following Java code is causing a runtime error: "unrecognized selector sent to instance"

ParameterizedType listTypeParams = (ParameterizedType) f.getGenericType();
Class<?> listType = (Class<?>) **listTypeParams.getActualTypeArguments**()[0];

The generated Obj-C code is:

id<JavaLangReflectParameterizedType> listTypeParams = (id<JavaLangReflectParameterizedType>) cast_check([f getGenericType], JavaLangReflectParameterizedType_class_());
            IOSClass *listType = (IOSClass *) cast_chk(IOSObjectArray_Get(nil_chk([((id<JavaLangReflectParameterizedType>) nil_chk(listTypeParams)) getActualTypeArguments]), 0), [IOSClass class]);

Can you offer any help?

Thanks,
Chad Lowe

**Comment by tomball** [comment] 2018-01-31 23:59
What you posted isn't code generated by j2objc (at least not in any recent version), as the first line should read `id<JavaLangReflectParameterizedType> listTypeParams...`. An object of type id is similar to Java's Object type, very minimal. Adding the JavaLangReflectParameterizedType protocol to the declaration tells the compiler that the id responds to ParameterizedType methods. Without the protocol, the compiler will correctly complain about an "unrecognized selector sent to instance".

The [ParameterizedTypeTest's testParameterizedMemeber() unit test](https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/harmony-tests/src/test/java/org/apache/harmony/tests/java/lang/reflect/ParameterizedTypeTest.java#L65) has code very similar to what you posted, and when generated has the `id<JavaLangReflectParameterizedType>` declaration. I also created this simple test, and verified it has the protocol declaration, and that it executes the same with the JVM and on macOS:

```
import java.lang.reflect.*;

class ActualTypeArgsTest {
  static class E<T> {}
  static class F<T> {
    E<T> e;
  }

  public static void main(String... args) throws Exception {
    Field f = F.class.getDeclaredField("e");
    ParameterizedType parameterizedType = (ParameterizedType) f.getGenericType();
    Type[] typeArgs = parameterizedType.getActualTypeArguments();
    System.out.println("typeargs[0]: " + typeArgs[0].getTypeName());
  }
}
```

I'm closing this as "cannot reproduce", but if you can add a Java source file that demonstrates this problem, please reopen this issue.

**Closed by tomball** 2018-01-31 23:59 UTC
Labels: cannot reproduce
