### ISSUE TITLE
Variable name collision in generated code

### ISSUE THREAD

**Issue by lekz112** [google/j2objc#800] opened 2016-10-04 00:38 UTC
Using released version 1.1
If we have lambda expression that captures variable named "result" we would get uncompilable code because this name is also used for resulting LambdaBase variable.

Example java code:
```java
import java.util.ArrayList;
import java.util.List;

public class Test {
	public List<String> test() {
		final List<String> result = new ArrayList();
		Runnable run = () -> {
			result.add("Test");
		};
		run.run();
		return result;
	}
}
```
After translating it we have a class with following function:
```objc
id<JavaLangRunnable> Test$$Lambda$1_get(id<JavaUtilList> result) {
  static dispatch_once_t token;
  static Class cls;
  dispatch_once(&token, ^{
    struct objc_method_description desc1 = protocol_getMethodDescription(@protocol(JavaLangRunnable), @selector(run), YES, YES);

    cls = CreatePossiblyCapturingClass(
    "Test$$Lambda$1", 1, (Protocol *[]){ @protocol(JavaLangRunnable)},
    2,
    (SEL []){ @selector(run), @selector(dealloc)},
    (IMP []){ (IMP)&Test$$Lambda$1_impl, (IMP)&Test$$Lambda$1_dealloc},
    (const char *[]){ desc1.types, "v@:"});
  });
  LambdaBase<JavaLangRunnable> *result = NSAllocateObject(cls, sizeof(Test$$Lambda$1_captures), nil);
  Test$$Lambda$1_captures *captures = (Test$$Lambda$1_captures *) &result->captures_;
  JreStrongAssign(&captures->result, result);
  return [result autorelease];
}
```
As you can see we have two variables named result: one is captured list, the other one is lambda instance.

Workaround: use any other name for captured variable.

**Comment by kstanger** [comment] 2016-10-04 16:22
Duplicate of #777

**Closed by kstanger** 2016-10-04 16:22 UTC
Labels: duplicate
