### ISSUE TITLE
TCP socket (java.net.Socket) completely broken in 2.0.4 and 2.0.5

### ISSUE THREAD

**Issue by aollin** [google/j2objc#937] opened 2018-01-29 12:26 UTC
Hi,

I've just run in to the following problem, reproducable in both 2.0.4 and 2.0.5. The 2.0.3 seems to work fine. Did not test from master branch as "make dist" fails for me. 

Basically what happens is that all calls to Socket object seem to fail due to an error in reflection. The "invalid type from metadata" gave me that clue.

import java.net.Socket;
…
mSocket = new Socket();
mSocket.setSoTimeout(10000);
mSocket.connect(new InetSocketAddress(InetAddress.getByName(mHostname), mPortNumber));
if (mSocket.isConnected()) {
…

Exception in thread "TcpDevice" java.lang.AssertionError: invalid type from metadata LJavaNetServerSocket;
	at 0x0000000103298b57 java.lang.AssertionError.<init>() + 45
	at 0x000000010360fba8 java.lang.reflect.Field.get() + 37
	at 0x0000000103567608 java.net.AbstractPlainSocketImpl.create() + 56
	at 0x0000000103447b4c java.net.Socket.createImpl() + 74
	at 0x0000000103447ea7 java.net.Socket.getImpl() + 43
	at 0x0000000103448d8c java.net.Socket.setSoTimeout() + 62

**Comment by aollin** [comment] 2018-01-29 12:29
I'm using the official pre-build versions.

**Comment by aollin** [comment] 2018-02-15 14:18
No response?

**Comment by tomball** [comment] 2018-02-15 16:40
"invalid type from metadata" is a useless error message, for this it should read something like "class not found: <missing class name>" (I'll fix it separately).

This issue is caused by the update to the OpenJDK version of java.net. Generally this is an improvement because it's more compatible with the JRE and Android than the earlier code based Apache Harmony, but it uses reflection more than the old code did. This code failed because java.net.ServerSocket was only referenced by reflection, and that class wasn't linked into your app since there weren't any explicit references to it.

A workaround is to add the -ObjC flag to your app's Other Linker Flags. This causes all JRE classes to be included in your app, whether there are explicit references or not. That should get you unblocked.

**Comment by tomball** [comment] 2018-02-15 19:15
Fixed in current source. [Here are the instructions to create a release bundle.](https://developers.google.com/j2objc/guides/building-j2objc)

**Closed by tomball** 2018-02-15 19:15 UTC

**Comment by aollin** [comment] 2018-02-16 09:20
Thank you for the fix & explanation!
