### ISSUE TITLE
private static field access with reflection?

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#767] opened 2016-07-19 02:06 UTC
In keeping with the strange reflection issues theme, this fell out of gson testing.

Class<?> unsafeClass = Class.forName("sun.misc.Unsafe");
Field f = unsafeClass.getDeclaredField("theUnsafe");
f.setAccessible(true);
final Object unsafe = f.get(null);

The 'unsafe' at the end has address 0x0. Using it fails, as you might expect.

The gson version is being modified for j2objc specifically, so the workaround was simply referencing Unsafe directly in code rather than from 'Class.forName', but I assume there could be similar issues in other cases.  Will try to add a more general, less obscure example and see if the same issue occurs.

Workaround code, for reference:

final Object unsafe = Unsafe.getUnsafe();
Class<?> unsafeClass = unsafe.getClass();

That worked fine. In context, it allows gson to inflate classes without a no-arg constructor.

https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/UnsafeAllocator.java#L34

**Comment by tomball** [comment] 2016-07-21 20:42
This is caused by "theUnsafe" getting initialized in the class's +initialize method, but that method not being called. I think the fix is for Class.forName() to invoke the class's +initialize method, and will test it this afternoon.

**Comment by kstanger** [comment] 2016-08-02 13:25
Fixed in [current](https://github.com/google/j2objc/commit/96d6723b7798379c7cd2626dff61ad3c19d56a05) [source](https://github.com/google/j2objc/commit/860ec4c4c3df96eec9e3e9db55653a87bf3ac521). Also fixed in J2ObjC 1.1

**Closed by kstanger** 2016-08-02 13:25 UTC
