### ISSUE TITLE
java.net.IDN#toASCII is incorrect

### ISSUE THREAD

**Issue by mikelikespie** [google/j2objc#938] opened 2018-01-29 19:49 UTC
Any string that is given, gets a `-` appended to it. I'm pretty sure nativeIDN#toASCII is broken. I'd submit a PR, but not exactly sure how it's supposed to be implemented.

Regardless, this test fails

```
    String result = NativeIDN.toASCII("foo", 0);
    Assert.assertEquals("foo", result);
```

with

```
junit.framework.ComparisonFailure: 
Expected :foo
Actual   :foo-
```

**Comment by tomball** [comment] 2018-01-30 17:37
Either I didn't convert the pseudo or C code in https://www.ietf.org/rfc/rfc3492.txt correctly, or else the spec used to require the trailing delimiter and has changed. I suspect the latter, as the Punycode encoders in ICU4C and ICU4J appear to be much more complex than the encoder described in the spec.

As far as how best to fix this, the best approach IMO is to first create or find unit tests that provide enough coverage, then fix NativeIDN to pass them. I'll start by adding the Android libcore library's two IDNTest classes, then create a separate test that uses a table of Unicode and matching Punycode ASCII strings.

**Comment by tomball** [comment] 2018-02-04 00:44
The problem isn't with the punycode encoder, it's that IDN is different from straight punycode. Using [bestiejs/punycode.js](https://github.com/bestiejs/punycode.js/), punycode.encode('foo') returns 'foo-' (like NativeIDN does), but punycode.toASCII('foo') returns the IDN 'foo'. Since punycode.js is well tested (it used to be part of node.js), I'll look into adapting its toASCII() and toUnicode() methods to NativeIDN.

**Comment by tomball** [comment] 2018-02-05 20:35
Fixed in current source.

**Closed by tomball** 2018-02-05 20:35 UTC

**Comment by mikelikespie** [comment] 2018-02-05 22:59
@tomball thanks for fast turnaround!
