### ISSUE TITLE
NumberFormat.getCurrencyInstance().format has no effect, neither does DecimalFormat

### ISSUE THREAD

**Issue by sadevelopment** [google/j2objc#404] opened 2014-09-23 10:31 UTC
We have been trying to use NumberFormat.getCurrencyInstance(Locale) to format prices but with no effect.

For instance

BigDecimal price = new BigDecimal("10.00");
NumberFormat.getCurrencyInstance(Locale.UK).format(price);

Will just return 10.00 instead of £10.00.

The following code for DecimalFormat, where we would like to show just 10 instead of 10.00 if the exponent is 0 still shows 10.00;

{        
        DecimalFormat format = new DecimalFormat("0.##");
        format.setMaximumFractionDigits(2);
        if(price.doubleValue() % 1>0)
            format.setMinimumFractionDigits(2);
        return format.format(price); 
}

This works fine with Java/Android.

I have seen somewhere on the forums that NumberFormat or DecimalFormat has only had a minimal implementation to satisfy junit tests?

Could this be looked at as we have had to write our own formatter and we would like to keep this as consistent with the Java imlmentation as possible across iOS and Android?

**Comment by sadevelopment** [comment] 2016-03-03 17:52
Hi Tom,

I have finally got round to reverting our code to use the default locale's currency format using the following in Java:

NumberFormat currencyFormatter =
                NumberFormat.getCurrencyInstance(currencyLocale);

When converted this formats the price field correctly however it does not include the currency symbol. For instance the converted code listed below should output 12.00 € if price_ is set to 12.00, it only outputs 12.00.

    JavaUtilLocale *fr = JavaUtilLocale_forLanguageTagWithNSString_(@"fr_FR");
    JavaTextNumberFormat * french = JavaTextNumberFormat_getCurrencyInstanceWithJavaUtilLocale_(fr);
    
    NSLog(@"%@", [french formatWithId:price_]);

Any chance we could get a fix for this?

Best

Marcus

**Comment by tomball** [comment] 2016-03-05 00:16
OK, I found the problem is with how BigDecimals are formatted -- the same code using a double works fine. Not that you should use doubles for currency, of course, as [rounding errors creep in](https://www.youtube.com/watch?v=iLw9OBV7HYA). :-)

**Comment by sadevelopment** [comment] 2016-03-05 00:24
Hi Tom,

Thanks for the pointer I will Double check the type - no pun intended :). So going forward can we expect a fix? 

Best

Marcus

**Comment by tomball** [comment] 2016-03-05 00:44
Yes, it needs new tests and a code review first.

**Comment by sadevelopment** [comment] 2016-03-05 00:45
No problem  :)

**Comment by tomball** [comment] 2016-03-11 17:47
Fixed in current release.

**Closed by tomball** 2016-03-11 17:47 UTC
