### ISSUE TITLE
JDK not supported. Please set JAVA_HOME to JDK 1.8 or 11. I need help

### ISSUE THREAD

**Issue by gazyy1** [google/j2objc#1518] opened 2020-11-23 02:06 UTC
![1606097137657](https://user-images.githubusercontent.com/34432682/99924039-963cfb80-2d73-11eb-9562-b813c930bf3f.jpg)
![1606097142818](https://user-images.githubusercontent.com/34432682/99924040-989f5580-2d73-11eb-8c52-8977cbc3e4bf.jpg)
![1606097147532](https://user-images.githubusercontent.com/34432682/99924041-9937ec00-2d73-11eb-94d4-9c3dbdff4b98.jpg)

**Comment by tomball** [comment] 2020-11-29 17:45
Duplicate of #1513

**Closed** 2021-01-14 21:26 UTC
Labels: duplicate
