### ISSUE TITLE
Why do we functionize all constructors?

### ISSUE THREAD

**Issue by neocxi** [google/j2objc#508] opened 2015-03-31 05:17 UTC
First of all thank you so much for making this awesome project open source!

I have a question about the recent changes that make all constructors functionized -- I'm wondering what is the reason behind this? After this change is made, it's no longer possible to let one Java class inherits from an ObjectiveC class since there is no way to call the super initializers within a C function.

**Comment by kstanger** [comment] 2015-03-31 13:33
The motivation for functionizing constructors is for performance. The
function calls use less CPU instructions than the previous Objective-C
method calls.

It is still possible to call an Objective-C style initializer from a Java
constructor if the Java constructor is written with native code. Here's an
example from our own java.lang.Throwable implementation:
https://github.com/google/j2objc/blob/master/jre_emul/Classes/java/lang/Throwable.m#L137

Does this work for your situation?

**Comment by neocxi** [comment] 2015-04-01 23:59
Hi kstanger,

Thank you for your explanation and it does make sense considering on Java side we have precise information about what initializers are being invoked.

Maybe I should have explained the situation a little bit more clearly. We are maintaining a j2objc fork that supports calling into platform specific APIs (UIkit etc) so it's common to invoke a super constructor that's actually not a Java method, which makes functionizing these constructors difficult (even though one could still manage it with cryptic functions like objc_msgSendSuper). It's good to know that the motivation for functionizing constructors is performance, so we'd just fall back to the usual initializers when we need to deal with ObjC native class's initializers.

I'm wondering if you'd be interested in merging this fork to upstream so if someone wants to use platform-specific APIs, they could do so in Java?

**Comment by kstanger** [comment] 2015-04-02 12:44
So you must be creating Java stub classes for all the platform APIs you
support, is that correct?

This sounds like it might be burdensome to maintain as the iOS APIs evolve,
so I'm hesitant about merging unless there's value to many of our users. Is
your fork public?

**Comment by kstanger** [comment] 2015-04-02 12:45
Closing, since this is working as intended.

**Closed by kstanger** 2015-04-02 12:45 UTC
