### ISSUE TITLE
Included guava library contains source java files not compiled class files

### ISSUE THREAD

**Issue by MohammadHejazi** [google/j2objc#716] opened 2016-02-22 13:30 UTC
In v1.0.1, the included guava library jar file (`libs/j2objc_guava.jar`) contains the java source files not compiled class files (as it used to do). Is this intended?

**Comment by tomball** [comment] 2016-02-23 17:24
Duplicate of issue #711, fixed in current source. If you don't want to rebuild the latest source, you can use the [Guava release 19.0 jar](http://search.maven.org/#artifactdetails%7Ccom.google.guava%7Cguava%7C19.0%7Cbundle) instead of the j2objc version (they're now the same.

**Closed by tomball** 2016-02-23 17:24 UTC
Labels: duplicate
