### ISSUE TITLE
java converted types are not protected during j2Objc compile

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [google/j2objc#880] opened 2017-09-19 23:56 UTC
We had a function with the signature:

private static double calerf(double X, int jint);

It generated a method signature like:

jdouble calerfWithDouble_withInt_(jdouble X, jint jint)

This function had several variables of integer type which were of course converted to jint.

The variable name and the jint type thus caused a clash and a compile error which indicated it was a missing token.

During the j2objc compile process it would likely be better to emit an error during these clashes for the reserved variable types that are used during translation.

**Comment by kstanger** [comment] 2017-09-20 17:23
Could you include the contents of your "calerf" method, or at least the statement that produced the error, and the text of the compile error? Though this seems like a legitimate issue, I can't reproduce a compile error when I try naming a variable "jint".

**Comment by jonl-percsolutions-com** [comment] 2017-09-21 02:38
it was a for loop..

IE,
```
for (jint i=0; i< some contstant; i++) {
...some code...
}

```
So in this case, jint var name conflicts with the variable type and produces an error that there is a missing ';'.

**Comment by kstanger** [comment] 2017-09-21 14:23
Thanks, I was able to reproduce the issue with a for loop. I have a fix ready internally. If you don't want to wait for it, you can add the conflicting type names to our [list of reserved names](https://github.com/google/j2objc/blob/master/translator/src/main/resources/com/google/devtools/j2objc/reserved_names.txt) and [rebuild j2objc](https://developers.google.com/j2objc/guides/building-j2objc).

**Comment by kstanger** [comment] 2017-09-22 14:31
Fixed in current source.

**Closed by kstanger** 2017-09-22 14:31 UTC
