### ISSUE TITLE
HashMap values() function crash

### ISSUE THREAD

**Issue by kingxt** [google/j2objc#561] opened 2015-07-01 02:28 UTC
public Map<Long, Integer> getMultipleUnreadCount(final long ownerUid, final Set<Long> groupIdSet)
    {
        final Map<Long, Integer> unreadCountMap = new HashMap<>();
        for (final long groupId : groupIdSet)
        {
            unreadCountMap.put(groupId, 10);
        }

        return unreadCountMap;
    }

    public int getTotalUnreadCount(final long ownerUid, final Set<Long> groupIds)
    {
        final Collection<Integer> unreadCountSet = getMultipleUnreadCount(ownerUid, groupIds).values();
        int totalCount = 0;
        for (final Integer count : unreadCountSet)
       	{
       		totalCount += count;
       	}
        return totalCount;
    }

If I build the code in Xcode release mode, The above code will crash at countByEnumeratingWithState:objects:count function for the iterator  (final Integer count : unreadCountSet).
But if change the code from
final Collection<Integer> unreadCountSet = getMultipleUnreadCount(ownerUid, groupIds).values();
to
Map<Long, Integer> result = getMultipleUnreadCount(ownerUid, groupIds);
final Collection<Integer> unreadCountSet = result.values();
everything get right.

I think this is because the compiler will inject release memory without any reference in release mode.

**Comment by kstanger** [comment] 2015-07-03 17:00
The collection returned by Map.values() holds only a weak reference to the
target Map. The reason for this is to avoid a memory leak caused by a
retain cycle.

The solution (as you've discovered) is to hold a reference to the map for
at least as long as you need to use the values() collection.
I would also recommend compiling your translated code without ARC. In
non-ARC mode, objects will stick around until the autorelease pool is
drained.

**Comment by kstanger** [comment] 2015-07-03 17:01
Closing, since this is expected behavior, and required to avoid leaks.

**Closed by kstanger** 2015-07-03 17:01 UTC
