### ISSUE TITLE
KeyPairGenerator doesn't generate private key

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1038] opened 2019-04-26 11:07 UTC
Hi,

this sniplet:

```java
        try {
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("RSA");
            KeyPair pair = keyGen.generateKeyPair();
            System.out.println(pair.getPrivate().getEncoded());
            System.out.println(pair.getPublic().getEncoded());
       } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
```

returns null for `pair.getPrivate().getEncoded()` and real data for `pair.getPublic().getEncoded()`. It works correctly in Java (Android). Where is the catch?

**Comment by antonio-cortes-perez** [comment] 2019-04-26 14:39
We do not have full support of security features. It has been growing thanks to contributions. For example, we recently added a SslSocket client based on a reference implementation provided by a J2ObjC user.

In case you have a chance to help us expand our support, you could start exploring the code here:
https://github.com/google/j2objc/blob/master/jre_emul/Classes/com/google/j2objc/security/IosRSAKeyPairGenerator.java

I am going to close this as duplicate of #865. In that issue, they were able to generate the key pair by adding this line after get instance:
keyGen.initialize(1024);
But the generated keys were always the same.

**Closed by antonio-cortes-perez** 2019-04-26 14:39 UTC

**Comment by tomball** [comment] 2019-05-15 22:00
The issue is that [iOS doesn't provide a way to export private key data](https://forums.developer.apple.com/thread/42470). I was able to get a data blob using SecKeyCopyExternalRepresentation(), but it consists of a single sequence rather than a pair of sequences with the exponent and modulus like the public key data has. Here's the change to IosRSAKey.IosRSAPrivateKey.getEncoded(), new as of iOS 10.0, in case you can make sense of that data:
```
  public native byte[] getEncoded() /*-[
    CFErrorRef errorRef = NULL;
    CFDataRef dataRef =
        SecKeyCopyExternalRepresentation((SecKeyRef)(self->iosSecKey_), &errorRef);
    NSData *privateKey = (errorRef == NULL) ? (NSData *)dataRef : nil;

    IOSByteArray *bytes = nil;
    if (privateKey.length > 0) {
      bytes = [IOSByteArray arrayWithBytes:(jbyte *)privateKey.bytes count:privateKey.length];
      [privateKey release];
    }
    return bytes;
  ]-*/;
```
