### ISSUE TITLE
Java8 DateTimeFormatter behaving differently 

### ISSUE THREAD

**Issue by vinayhegde2013** [google/j2objc#1383] opened 2020-07-16 11:20 UTC
First example works with milliseconds delimiter:

```
ZonedDateTime timeAsUTC1 = LocalDateTime.from(DateTimeFormatter.ofPattern("yyyyMMddHHmmss-SSS").parse("20190902165550-091")).atZone(ZoneId.of("UTC"));
System.out.println(timeAsUTC1);
```

But the second one without delimiter:

```
ZonedDateTime timeAsUTC2 = LocalDateTime.from(DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS").parse("20190902165550091")).atZone(ZoneId.of("UTC"));
System.out.println(timeAsUTC2);
```
fails with the following exception:

```
Exception in thread "main" java.time.format.DateTimeParseException: Text '20190902165550091' could not be parsed at index 0
    at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
    at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
```

I am using java8. Any idea?

**Comment by tomball** [comment] 2020-07-19 17:18
What version are you using? 2.6? Head? We recently updated java.time.* to the latest Android source, so if it's a recent change that could be the issue.

**Comment by tomball** [comment] 2020-07-19 17:47
If you build and run your test with Java 8, it fails with the same error, and is fixed in Java 11. 

However, the j2objc JRE emulation library is a fork of Android's libcore library, which is based on Java 8. That means that your test will also fail on any version Android that supports java.time. 

So even though this is a real bug, it's more important that j2objc emulate Android's current JRE to support cross-platform code. So this is closed as "works as intended," even though it's a bug that will be fixed in a future Android release and then merged into j2objc's fork.

**Closed by tomball** 2020-07-19 17:47 UTC
Labels: works as intended

**Comment by vinayhegde2013** [comment] 2020-07-20 16:11
Thanks tomball, So issue with java8, if I upgrade to java11 then it wont cause any issue.
