### ISSUE TITLE
Non-public classes included in JRE.framework/JRE.h

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [google/j2objc#896] opened 2017-10-10 23:42 UTC
Working on porting my app to j2objc.  Part of it is written in swift.  As such I created a bridging header and attempted to import the JRE.h in the bridging header.  On doing so, I receive an error 'java/net/AbstractPlainDatagramSocketImpl.h' file not found, in PlainDatagramSocketImpl.h.  Looking at the framework directory, it is indeed not there.  It is also not in include/java/net folder. This is with version 2.0.4.1.

I have worked around the issue by only adding the imports I actually needed to the bridging header.

**Comment by tomball** [comment] 2017-10-17 15:53
The problem is that PlainDatagramSocketImpl.java is incorrectly listed as a public file in j2objc/jre_emul/jre_sources.mk. As a workaround, delete the "#include <java/net/PlainDatagramSocketImpl.h>" link in `j2objc/frameworks/JRE.framework/Headers/JRE.h`.

**Comment by Lukasz2891** [comment] 2017-10-18 09:20
Probably it's needed to remove other <*Impl.h> as a workaround. 
I needed to remove 3 of the headers.

**Comment by tomball** [comment] 2017-10-18 15:51
Right, the Plain*Impl and ProxyselectorImpl classes were all package-private. SocketImpl* and DataSocketImpl* are public, though.

**Comment by tomball** [comment] 2017-10-18 15:55
Fixed in current source.

**Closed by tomball** 2017-10-18 15:55 UTC
