### ISSUE TITLE
EXC_BAD_ACCESS new in 0.9.5

### ISSUE THREAD

**Issue by zetti68** [google/j2objc#479] opened 2015-01-16 13:18 UTC
Hello,
first of all you made a very good job.

But unfortunately the new version of libjre_emul.a contains a critical new runtime bug (iOS app crashes with EXC_BAD_ACCESS).

Java code:
List[] two_lists_in_an_array = { new ArrayList\<Double\>(), new ArrayList\<Double\>() };
int size0 = two_lists_in_an_array[0].size();   <- New crash in 0.9.5, works correct in 0.9.4!

I know it is not the best code, but it works in Java/Android without problems.

The generated code for this line is equal in 0.9.4 and 0.9.5.

Best regards
zetti68

**Comment by kstanger** [comment] 2015-01-16 17:45
This is a duplicate of Issue 440.

**Closed by kstanger** 2015-01-16 17:45 UTC
Labels: duplicate

**Comment by tomball** [comment] 2015-01-16 17:59
To get a quick fix, clone this project, then run "make dist" in its top directory to create a new distribution bundle.
