### ISSUE TITLE
Annotation declarations fail when arrays of other annotations are default values

### ISSUE THREAD

**Issue by RishiUppala** [google/j2objc#471] opened 2015-01-10 11:44 UTC
<Using J2ObjC 0.9.5>

In a java file i have the following code:
   @XmlElements({
           @XmlElement(name = "adminNote", type = AdminNoteInstance.class),
           @XmlElement(name = "inboundNote", type = InboundNoteInstance.class),
           @XmlElement(name = "outboundNote", type = OutboundNoteInstance.class)
   })
   private List<NoteInstance> notes = new ArrayList<NoteInstance>();

where the XmlElements class is as follows:

@Retention(RUNTIME) @Target({FIELD,METHOD})
public @interface XmlElements {
   /**
    * Collection of @{@link XmlElement} annotations
    */
   XmlElement[] value();
}

And the XmlElement class is as follows:

package javax.xml.bind.annotation;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Retention(RUNTIME) @Target({FIELD, METHOD})
public @interface XmlElement {
    /**
     * Name of the XML Schema element.
     * <p> If the value is "##default", then element name is derived from the
     * JavaBean property name.
     */
    String name() default "##default";

    /**
     * Customize the element declaration to be nillable.
     * <p>If nillable() is true, then the JavaBean property is
     * mapped to a XML Schema nillable element declaration.
     */
    boolean nillable() default false;

    /**
     * Customize the element declaration to be required.
     * <p>If required() is true, then Javabean property is mapped to
     * an XML schema element declaration with minOccurs="1".
     * maxOccurs is "1" for a single valued property and "unbounded"
     * for a multivalued property.
     * <p>If required() is false, then the Javabean property is mapped
     * to XML Schema element declaration with minOccurs="0".
     * maxOccurs is "1" for a single valued property and "unbounded"
     * for a multivalued property.
     */

    boolean required() default false;

    /**
     * XML target namespace of the XML Schema element.
     * <p>
     * If the value is "##default", then the namespace is determined
     * as follows:
     * <ol>
     *  <li>
     *  If the enclosing package has {@link XmlSchema} annotation,
     *  and its {@link XmlSchema#elementFormDefault() elementFormDefault}
     *  is {@link XmlNsForm#QUALIFIED QUALIFIED}, then the namespace of
     *  the enclosing class.
     *
     *  <li>
     *  Otherwise "" (which produces unqualified element in the default
     *  namespace.
     * </ol>
     */
    String namespace() default "##default";

    /**
     * Default value of this element.
     *
     * <p>
     * The '\u0000' value specified as a default of this annotation element
     * is used as a poor-man's substitute for null to allow implementations
     * to recognize the 'no default value' state.
     */
    String defaultValue() default "\u0000";

    /**
     * The Java class being referenced.
     */
    Class type() default DEFAULT.class;

    /**
     * Used in {@link XmlElement#type()} to
     * signal that the type be inferred from the signature
     * of the property.
     */
    static final class DEFAULT {}
}

But while translating to ObjC files, got the below exceptions:

translating com/assessment/model/QuestionGroupResult.java
Exception in thread "main" java.lang.ClassCastException: com.google.devtools.j2objc.ast.NormalAnnotation cannot be cast to com.google.devtools.j2objc.ast.Expression
	at com.google.devtools.j2objc.ast.ArrayInitializer.<init>(ArrayInitializer.java:33)
	at com.google.devtools.j2objc.ast.TreeConverter.convertInner(TreeConverter.java:77)
	at com.google.devtools.j2objc.ast.TreeConverter.convert(TreeConverter.java:56)
	at com.google.devtools.j2objc.ast.SingleMemberAnnotation.<init>(SingleMemberAnnotation.java:26)
	at com.google.devtools.j2objc.ast.TreeConverter.convertInner(TreeConverter.java:177)
	at com.google.devtools.j2objc.ast.TreeConverter.convert(TreeConverter.java:56)
	at com.google.devtools.j2objc.ast.BodyDeclaration.<init>(BodyDeclaration.java:38)
	at com.google.devtools.j2objc.ast.FieldDeclaration.<init>(FieldDeclaration.java:31)
	at com.google.devtools.j2objc.ast.TreeConverter.convertInner(TreeConverter.java:122)
	at com.google.devtools.j2objc.ast.TreeConverter.convert(TreeConverter.java:56)
	at com.google.devtools.j2objc.ast.AbstractTypeDeclaration.<init>(AbstractTypeDeclaration.java:40)
	at com.google.devtools.j2objc.ast.TypeDeclaration.<init>(TypeDeclaration.java:31)
	at com.google.devtools.j2objc.ast.TreeConverter.convertInner(TreeConverter.java:208)
	at com.google.devtools.j2objc.ast.TreeConverter.convert(TreeConverter.java:56)
	at com.google.devtools.j2objc.ast.CompilationUnit.<init>(CompilationUnit.java:72)
	at com.google.devtools.j2objc.ast.TreeConverter.convertCompilationUnit(TreeConverter.java:28)
	at com.google.devtools.j2objc.TranslationProcessor.processUnit(TranslationProcessor.java:129)
	at com.google.devtools.j2objc.FileProcessor.processSource(FileProcessor.java:217)
	at com.google.devtools.j2objc.TranslationProcessor.processSource(TranslationProcessor.java:118)
	at com.google.devtools.j2objc.FileProcessor.processJarFile(FileProcessor.java:182)
	at com.google.devtools.j2objc.FileProcessor.processSourceFile(FileProcessor.java:100)
	at com.google.devtools.j2objc.FileProcessor.processFile(FileProcessor.java:70)
	at com.google.devtools.j2objc.FileProcessor.processFiles(FileProcessor.java:61)
	at com.google.devtools.j2objc.TranslationProcessor.processFiles(TranslationProcessor.java:102)
	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:192)
make: *** [translate] Error 1
Command /usr/bin/make failed with exit code 2

**Comment by tomball** [comment] 2015-01-10 23:07
Duplicate of issue 470, though I included this test in addition to 470's. Thanks for the detailed report.

**Closed by tomball** 2015-01-10 23:07 UTC
Labels: duplicate, Pending
