### ISSUE TITLE
j2objc cannot compile code that can be compiled with Java 8

### ISSUE THREAD

**Issue by zubchenok** [google/j2objc#825] opened 2017-01-06 17:04 UTC
I found this code pattern two times in RxJava library. It compiles and works in Java, but cannot be compiled/translated with j2objc.

```
public class Hello
{
    public static class Bar
    {
    }

    public static class Foo<T>
    {
    }

    public static void main(String[] args)
    {
        Foo<? extends Bar> first = null;
        Foo second = null;
        Foo<Bar> result = Hello.create1(first, second); // j2obc Compilation fails here
    }

    private static <T> Foo<T> create1(Foo<T> sourceA, Foo<T> sourceB)
    {
        return null;
    }
}
```
j2objc fails:

> $ j2objc Hello.java
> error: Hello.java:15: Type mismatch: cannot convert from Hello.Foo<capture#1-of ? extends Hello.Bar> to Hello.Foo<Hello.Bar>

---
References to RxJava sources that fail:
1. [https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java#L131](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java#L131)
`FlowableReplay.java:131: error: Type mismatch: cannot convert from ConnectableFlowable<capture#22-of ? extends T> to ConnectableFlowable<T>`
2. [https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java#L126](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java#L126)
`ObservableReplay.java:126: error: Type mismatch: cannot convert from ConnectableObservable<capture#19-of ? extends T> to ConnectableObservable<T>`

**Comment by zubchenok** [comment] 2017-01-06 17:17
Any ideas how to fix it without modifications to RxJava?

**Comment by kstanger** [comment] 2017-01-06 18:02
There's a good chance these errors will be fixed when we switch our parser front-end from Eclipse JDT to Javac. This is coming soon.

**Comment by zubchenok** [comment] 2017-01-06 18:14
I had seen Tom's message that javac front-end will be in a month later. It was on Dec 13. Do you have any update on the date? I'll be happy to run javac tests on my projects.

**Comment by tomball** [comment] 2017-01-06 19:22
Has it been a month? I realize the time zone in Belarus is ahead of
California's, but by a whole week? ;-)

The j2objc distribution now builds and passes its tests, and we're now
verifying that all internal clients build and test successfully. We've
pushed out all of our changes, so you can try the new front-end by running
"export J2OBJC_FRONT_END=JAVAC" in your bash shell (or set that environment
variable however you usually do). If that's inconvenient, edit Options.java
to change the JDT default front-end
<https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/Options.java#L183>
to JAVAC. Generated files are (or should be) essentially the same, though
diff will show some comment differences. Please let us know what your
testing finds.

**Comment by zubchenok** [comment] 2017-01-06 19:35
$ export J2OBJC_FRONT_END=JAVAC
$ ./j2objc Hello.java
error: Hello.java:15: Type mismatch: cannot convert from Hello.Foo<capture#1-of ? extends Hello.Bar> to Hello.Foo<Hello.Bar>

Seems v1.2 is not compatible with JAVAC yet. So I have to pull and build, I will do it and update you soon.

**Comment by zubchenok** [comment] 2017-01-08 19:44
My test file has been successfully compiled with JAVAC.
I will try to translate the whole project and test how it works tomorrow.

**Comment by tomball** [comment] 2017-01-10 17:35
I just verified that both your test class and the RxJava project build with the javac front-end. To try this, pull or create your j2objc project clone to get the latest source, run "make -j4 dist" in the top-level directory, then run j2objc with the -Xuse-javac flag or the J2OBJC_FRONT_END=JAVAC environment variable. I did the latter, cloned the RxJava and reactive-streams-jvm projects, then ran the following build command in the RxJava top directory:

$ j2objc -l -d /tmp/reactive -sourcepath src/main/java:../reactive-streams-jvm/api/src/main/java \\
    `find src/main/java ../reactive-streams-jvm/api/src/main/java -name *.java

We'll close this issue when the javac front-end becomes the default.

**Comment by zubchenok** [comment] 2017-01-13 03:32
After a busy start of the week, I've finally did tests. Too many differences if I compare the latest 1.2 release with the latest j2objc version. So I first translated all code with the latest j2objc version and Eclipse JDT, and then with javac.

My findings:
1. yes, differences in format of comment
2. many classes have changed modifiers of J2ObjcClassInfo: 0x8008 to 0x8018 (did not find what is 0x10 bit for, could you tell?)
3. [!] we have several modules, and when I use javac front-end, base module compiles, but others - don't. Dependent modules have sources of base module in class path only. this is a real my problem now.
4. sometimes another order of methods
5. several local variables defined in single line are all translated each in its own line
6. original parameter names in constructors (was param0, now real variable name)
7. found differences in comparators implementation/names
8. differences in casting: when you set value to a field of base class:
```
B extends A, A has a field
method(B b);
b.field = 123; -- here is casting and nil check, javac casts to B, Eclipse JDT casts to class A
```
9. [!] missed initialization in anonymous class like
```
    private static final Map<String, String> test = new HashMap<String, String>()
    {{
        put("123", "123");
    }};
```
... to be continued :)

Summary: the real problems are points 3 & 9.
I would be happy to provide more details on any case on your request.
If I can compile and run, I'll probably tell you more.

**Comment by tomball** [comment] 2017-01-13 16:49
Regarding point 3: j2objc was designed to "work alike" javac as much as
possible, sharing the same flags -classpath, -sourcepath, -processorpath,
etc. For whatever reasons, we found that developers have an easier time
fixing source and class path issues if they start with a javac command, and
get that to compile successfully first. Our support goal has therefore been
to support project compilation issues when the same source can be compiled
using the same flags with javac.

My guess is that the original way j2objc was invoked to build your project
would not have worked if "javac" were substituted for "j2objc". Would you
please try building your project with javac, using the source and class
paths that caused point 3 to fail? If javac compiles with the original
paths but j2objc doesn't, then we have a front-end setup issue.

**Comment by tomball** [comment] 2017-01-14 21:31
The 0x10 modifier is [FINAL](https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/reflect/Modifier.java#L285). I ran j2objc over the test class below with both front-ends and compared their .h and .m files. The only difference was that the javac anonymous class is marked as FINAL, while the JDT one isn't (all other classes had identical declarations, implementations, and metadata).

Since anonymous classes can't be extended, they are final whether their modifiers have the FINAL flag or not. Since anonymous class files are marked FINAL (use javap -v to see a class's flags), I think this is a harmless JDT bug and the javac front-end is correct. I'd like to therefore close point 2.

```
import java.io.Serializable;

class ClassTypes {
  static class InnerClass {}
  static interface InnerInterface {}
  static enum InnerEnum { FOO; }
  static @interface InnerAnnotation {}
  static final Serializable anonymousClass = new Serializable() {};
}
```

**Comment by tomball** [comment] 2017-01-14 21:39
I can replicate point 9 (thanks for the example), and will fix it this weekend. Although we tested literally thousands of lines of code, this is probably the first double-brace initialization run through the new front-end. Even though [that's considered an anti-pattern](https://blog.jooq.org/2014/12/08/dont-be-clever-the-double-curly-braces-anti-pattern/), we'll still fix it before switching the default. Even nasty code that compiled before needs to be supported! :-)

**Comment by zubchenok** [comment] 2017-01-15 12:13
3. It's my wrong configuration issue. As you suggested Tom, I checked javac with my old configuration - it does not compile when I add source folders to classpath. As well as new j2objc doesn't translates with the -Xuse-javac flag. However j2objc with Eclipse JDT translates successfully in this case.
(I'm not sure if you guys are interested in this minor issue with Eclipse JDT)

A few my notes more:

10. Implementation of a private method was previously sometimes translated with usage of a static method, now is better. 👍 

11. Now we have parameter names in constructors, I have a constructor which has a parameter with name 'selector' which looks like reserved in ios. Probably the same note could be about parameter names for methods. 
I suspect and note it because you asked to write about what I find :), and AppCode highlights this parameter as reserved which actually could be an issue of AppCode. I guess it will compile without problems, but the general question is about valid/invalid reserved words for parameter names.

P.S. Currently I'm facing the issue with my new Java code, it translates to objective c successfully, but I cannot compile it. Trying to get what is going on...

**Comment by zubchenok** [comment] 2017-01-15 14:10
Currently I'm facing the issue with my new Java code, it translates to objective c successfully, but I cannot compile it. Trying to get what is going on... 
Update 1: I have the same problem with j2objc 1.2
Update 2: Heh... got 'j2objc: Argument list too long' error. Is there a way to get recursively for translation all java files in source folder? Or specify list of java files in file? What is the best way to handle long list of files for translation?

**Comment by zubchenok** [comment] 2017-01-15 19:14
12. Ok, finally I have the sample for you:
`
public class Base extends Factory
{
}
`
`
public class Item extends Base
{
}
`
`
public class Factory
{
    public class FactoryItem extends Item
    {
    }
}
`

This translates, but cannot compile, I tried:
j2objc 1.2
j2objc 1.3 Eclipse JDT front-end
j2objc 1.3 javac front-end

**Comment by zubchenok** [comment] 2017-01-15 19:19
Decided to add as separate point:
13. Update 4: [!!!] To avoid 'Argument list too long' I tried to use relative path to java sources, but j2objc hangs and uses 100% in some infinite loop... This looks like an issue. Reverting back to absolute paths for now.

**Comment by tomball** [comment] 2017-01-15 20:03
"Argument list too long:" both j2objc and javac support an @<file> flag --
just put all the flags and file names in a text file, and specify it with
an @ in front of its path.

**Comment by zubchenok** [comment] 2017-01-16 22:55
13. [!!!] There is a huge performance impact when javac translation is enabled. A little of statistics:

- My test with Eclipse JDT front-end completes in 1:36 (with --batch-translate-max=4, more than 4 has no more boost of performance, I have 4 cores CPU at my build machine (2 core with hyperthreading))

- With javac front-end translation is finished in 11 minutes (with --batch-translate-max=4). However when I set value of --batch-translate-max parameter equal to more than number of files to translate, like --batch-translate-max=65536, I got performance boost and all my test translates are completed just in 1:13.

So obviously there must be an issue that depends on number of files to translate. I believe now it will be easy to find a bug. :)

**Comment by tomball** [comment] 2017-01-18 19:37
We've disabled any batch maximum with the javac front-end (should be
submitted later today), since its performance is improved by compiling
everything at once, as you've noticed.

**Comment by kstanger** [comment] 2017-01-19 14:39
Regarding item #12, it looks like your example has circular inheritance dependencies that would cause #include cycles in your headers. Do you use the --no-segmented-headers flag? ([more info](http://j2objc.org/docs/Segmented-Headers.html))

**Comment by kstanger** [comment] 2017-01-19 15:11
Regarding #11, this doesn't appear to be a regression between JDT and JAVAC front ends. If there are specific reserved words that we're not renaming, could you file a separate issue?

**Comment by zubchenok** [comment] 2017-01-19 16:42
12. Yes, we use --no-segmented-headers.

**Comment by kstanger** [comment] 2017-01-19 17:16
--no-segmented-headers can result in compile errors if your Java code has class hierarchies that create circular include patterns. Try removing the flag if this is an issue for you. (or reorganize your Java code)

Thanks very much for your help with testing our Javac front end! I'm going to close this issue because I believe we've resolved all the items.

**Closed by kstanger** 2017-01-19 17:16 UTC
