### ISSUE TITLE
Proxy objects don't try to forward toString, equals, or hashCode

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#910] opened 2017-11-17 20:58 UTC
java.lang.reflect.Proxy instances created with Proxy.newProxyInstance do not attempt to forward some methods from Object to the InvocationHandler. I ran into this playing with Moshi. To see a sample of what I'm talking about, here's the proxy code:

https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/Types.java#L185

I worked around this by copy/pasting 'Proxy' to create a local class doing the same thing, but also overriding toString, equals, and hashCode, and routing them to the InvocationHandler. I assume this isn't working because those methods specifically have different implementation names on iOS, and my workaround functions for our purposes, but I wouldn't bet it's the most elegant way of handling this, so I didn't attempt a pull request of any kind.

https://github.com/doppllib/moshi/blob/doppl-1.5/moshi/src/main/java/com/squareup/moshi/MoshiProxy.java#L883

**Comment by tomball** [comment] 2017-11-17 23:25
If it's not too much trouble, please try testing with [j2objc 2.0](https://github.com/google/j2objc/releases/tag/2.0), as 2.0.1 updated Proxy.java to the OpenJDK version, to see if this is a regression.

**Comment by tomball** [comment] 2017-11-18 00:33
Is there a Moshi test that's failing, or example code? I built Moshi, but can't run most of its tests because assertj depends on java.nio.file and java.time.

**Comment by kpgalligan** [comment] 2017-11-18 01:10
There's a lot of tests that'll fail out of the box for moshi. Let me see if I can cook up something simple for a repro.

For version, the base is actually 2.0.4. I'd like to get it on to latest before filing bugs, but I looked at the diff and figured it should still be an issue.

**Comment by kpgalligan** [comment] 2017-11-18 02:13
Here's a pretty basic test that can be run easily. No moshi required. All 4 methods called in JVM, only 1 on iOS.

```java
interface ShowMe
  {
    int helloInt();
  }

  @Test
  public void showMeProxyTest()
  {
    final Set<String> methodNamesCalled = new HashSet<>();
    InvocationHandler invocationHandler = new InvocationHandler()
    {
      @Override
      public Object invoke(Object o, Method method, Object[] args) throws Throwable
      {
        String methodName = method.getName();
        System.out.println("METHOD_CALLED: " + methodName);
        methodNamesCalled.add(methodName);

        switch(methodName)
        {
          case "helloInt":
            return 123;
          case "equals":
            return o == args[0];
          case "hashCode":
            return 0;
          case "toString":
            return "hello";
          default:
            return method.invoke(o, args);
        }
      }
    };
    ShowMe showMe = (ShowMe)Proxy.newProxyInstance(getClass().getClassLoader(), new Class[] {ShowMe.class},
            invocationHandler);
    showMe.helloInt();
    showMe.toString();
    showMe.equals(new ShowMe()
    {
      @Override
      public int helloInt()
      {
        return 423;
      }
    });
    showMe.hashCode();

    assertTrue("toString wasn't called", methodNamesCalled.contains("toString"));
    assertEquals("Not all methods called", methodNamesCalled.size(), 4);
  }
```

**Comment by tomball** [comment] 2017-11-28 21:25
Good news of sorts: this test fails the same on 2.0 and the latest, so it's not a regression from upgrading to the OpenJDK version of Proxy. Now I just have to fix the current source. :-)

**Comment by tomball** [comment] 2017-12-02 17:39
Fixed in current source. This commit is a hack around not knowing how to filter NSObject methods, since the ObjC invocation support assumes all objects implement them and so doesn't call respondsToSelector: on them. If anyone knows of a better way to filter these methods, please either comment or send a pull request.

**Closed by tomball** 2017-12-02 17:39 UTC
