### ISSUE TITLE
Guava SingletonImmutableBiMap.inverse forms leaking-inducing reference cycle

### ISSUE THREAD

**Issue by RobinTD** [google/j2objc#898] opened 2017-10-16 16:12 UTC
According to the Instruments leak detector. This despite the `RetainedWith` annotation. Not sure if the `RetainedWith` rules hold there?

See: https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/SingletonImmutableBiMap.java
https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/RetainedWith

**Comment by kstanger** [comment] 2017-10-17 14:46
`@RetainedWith` is designed to work for this inverse pattern. I always treat Instruments leaks with a bit of skepticism. A more telling sign of a leak is if your app's memory usage is steadily rising. If it's not obvious, I usually write a simple test app and check its memory usage.

**Comment by tomball** [comment] 2017-10-19 00:13
+1

Closing with "works as intended," but please reopen if Instruments shows steadily rising SingletonImmutableBiMap related instances leaking.

**Closed by tomball** 2017-10-19 00:13 UTC
Labels: works as intended
