### ISSUE TITLE
IosHttpURLConnection doesn't handle multiple Set-Cookie response headers correctly

### ISSUE THREAD

**Issue by danieldickison** [google/j2objc#847] opened 2017-04-14 20:51 UTC
It seems that `HttpURLConnection`, when using a `CookieHandler`, doesn't handle multiple `Set-Cookie` response headers correctly. It seems to only capture one (probably the first) Set-Cookie.

I believe this is because `-[NSHTTPURLResponse allHeaderFields]` returns a String->String mapping, so multiple Set-Header headers ends up with a single entry where the value is a single comma-joined string of the individual header values. We save the single header entry during the NSURLDataSession delegate callback, and later on in `saveResponseCookies()` we call `cookieHandler.put(uri, getHeaderFieldsDoNotForceResponse());` and this seems to only parse one cookie.

I'm not sure what the best solution is, but doing `+[NSHTTPCookie cookiesWithResponseHeaderFields:forURL:]` does work correctly, when passing the value of `allHeaderFields`, so maybe using that and doing native handling for parsing the cookies and setting them in the CookieStorage is the way to go.

(I'm having compiling trouble compiling j2objc from source at the moment so I haven't tried to create a test case...)

**Comment by tomball** [comment] 2017-04-17 17:35
It looks like an issue with [NSHTTPURLResponse allHeaderFields]; check out the [third answer to this StackOverflow question](http://stackoverflow.com/questions/19066577/get-cookies-from-nshttpurlresponse), which suggests that some cookies are copied to the shared cookie store ([NSHTTPCookieStorage sharedHTTPCookieStorage]) and not returned via allHeaderFields.

My concern with only using [NSHTTPCookie cookiesWithResponseHeaderFields:forURL:] is that java.net.CookieHandler is a public API that would get skipped. Since the iOS shared cookie store maps very well to java.net.CookieHandler, I think the best approach is to define a IosCookieHandler that extends CookieHandler, uses the iOS shared cookie store for its data, and installs itself as the default CookieHandler.

I'm not sure the right way to test this, though. Will a MockWebServer response with multiple Set-Cookie: response headers be sufficient. Anything special about those cookies it should test?

**Comment by danieldickison** [comment] 2017-04-17 18:14
I don't think that particular issue is the problem here, since IosHttpURLConnection sets:

    request.HTTPShouldHandleCookies = false;

I'm pretty sure a mock web server returning multiple Set-Cookie headers will be sufficient to test this. (I'll drop a note in the forum about my j2objc building woes so I can try that.)

Here's a minimal iOS app that makes a request on https://bandcamp.com on launch and logs the headers (showing a concatenated Set-Cookie) and the multiple cookies that NSHTTPCookie parses it into:

```objc
- (void)applicationDidBecomeActive:(UIApplication *)application {
    NSMutableURLRequest *req = [NSMutableURLRequest requestWithURL: [NSURL URLWithString: @"https://bandcamp.com"]];
    req.HTTPShouldHandleCookies = NO;
    NSURLSession *ses = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration] delegate:self delegateQueue:nil];
    NSURLSessionDataTask *task = [ses dataTaskWithRequest:req];
    [task resume];
    [ses finishTasksAndInvalidate];
}

- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveResponse:(NSURLResponse *)response completionHandler:(void (^)(NSURLSessionResponseDisposition))completionHandler {
    
    NSLog(@"Headers:");
    NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *) response;
    for (NSString *key in [httpResponse allHeaderFields]) {
        NSString *value = [httpResponse allHeaderFields][key];
        NSLog(@"  %@: %@", key, value);
    }
    
    NSLog(@"Cookies:");
    for (NSHTTPCookie *cookie in [NSHTTPCookie cookiesWithResponseHeaderFields: httpResponse.allHeaderFields forURL: httpResponse.URL]) {
        NSLog(@"  %@", cookie);
    }
}
```

**Comment by tomball** [comment] 2017-04-17 21:17
Below is a simple test using your bandcamp URL, which prints all response headers and cookies. I was surprised to see that the JVM only had one cookie returned by the CookieHandler API, but it turns out that it only returns non-expired cookies, and 4 of the 5 cookies from bandcamp.com have a lifetime of 0 seconds. Does that sound right? 

```
import java.net.*;
import java.util.*;

class HttpTest {
  private static void printCookies(List<HttpCookie> cookies) {
    int i = 0;
    for (HttpCookie cookie : cookies) {
      System.out.println("   Name = " + cookie.getName());
      System.out.println("   Value = " + cookie.getValue());
      System.out.println("   Lifetime (seconds) = " + cookie.getMaxAge());
      System.out.println("   Path = " + cookie.getPath());
      System.out.println();
    }
  }

  public static void main(String... args) throws Exception {
    CookieManager cookieMgr = new CookieManager();
    cookieMgr.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
    CookieHandler.setDefault(cookieMgr);

    URL url = new URL("https://bandcamp.com");
    HttpURLConnection conn = (HttpURLConnection) url.openConnection();
    conn.getContent();  // forces response.

    System.out.println("CookieStore:");
    List<HttpCookie> cookies = cookieMgr.getCookieStore().getCookies();
    printCookies(cookies);

    System.out.println("Set-Cookie:");
    List<String> cookiesList = conn.getHeaderFields().get("Set-Cookie");
    for (String value : cookiesList) {
      printCookies(HttpCookie.parse(value));
    }
  }
}
```
I have enough here to test both JRE and iOS compliance. Thanks for your help!

**Comment by danieldickison** [comment] 2017-04-17 22:15
Those set-cookies that appear to have lifetime=0 should actually be alive, expiring at some time in the future. This is what the raw headers look like via curl:

```$ curl -I https://bandcamp.com
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html; charset=UTF-8
Set-Cookie: client_id=A2999AB60D601ADB79C5AF2FEE9ABC16FB6AF3BEB1823219A89714F752EAD5B1; domain=.bandcamp.com; path=/; expires=Sat, 17 Apr 2027 21:47:01 -0000
Set-Cookie: session=1%09t%3A1492465621%09r%3A%5B%22nilZ0f0x1492465621%22%5D; domain=.bandcamp.com; path=/; expires=Thu, 01 Jun 2017 21:47:01 -0000
Set-Cookie: unique_24h=223; domain=.bandcamp.com; path=/; expires=Tue, 18 Apr 2017 21:47:01 -0000
Set-Cookie: session=1%09t%3A1492465621%09r%3A%5B%22nilZ0f0x1492465621%22%5D; domain=.bandcamp.com; path=/; expires=Thu, 01 Jun 2017 21:47:01 -0000
Set-Cookie: BACKENDID=bender07-6; path=/; domain=.bandcamp.com
[...]
```

Interestingly they do get parsed correctly if you put that same code inside of an Android application, so that particular problem seems to be a desktop JRE problem.

And one last data point: the multiple cookies do get parsed and stored in the CookieManager correctly in our Android application (whereas only one cookie is stored in the j2objc-translated iOS code).

**Comment by tomball** [comment] 2017-04-17 23:06
I'm in the process of updating the old Apache Harmony java.net cookie
support classes with Android Nougat's OpenJDK-based classes. If you're
Android system is pre-Nougat then there may be an incompatibility coming.
:-)

The only-one-cookie with iOS issue is in IosHttpURLConnection, so that's
next.

**Comment by danieldickison** [comment] 2017-04-18 06:29
Indeed my test device is on Lollipop. Testing in Nougat shows those cookies failing to parse. Seems to stem from the use of `-0000` as the time zone in our cookie expires values while OpenJDK's `HttpCookie.parse()` strictly expects `GMT`. I guess we'll need to have our server emit the more standard `GMT` format since Nougat has already shipped with the stricter parsing even if OpenJDK becomes more lenient in the future.

In any case, thanks for looking into the IosHttURLConnection issue. It does seem like NSHttpCookieStorage could be used to implement CookieHandler.

**Comment by tomball** [comment] 2017-04-21 22:25
It looks like the problem is that NSURLSession combines multiple Set-Cookie field-values into an RFC2109 string, which uses commas to separate the cookies. This makes it difficult to split, since commas are also used in most date strings. java.net.HttpCookie.parse() bails, so there's a single Set-Cookie field with a string that is only partially parsed.

You're right that `[NSHTTPCookie cookiesWithResponseHeaderFields:forURL:]` works, but some developers get their cookies from a CookieStore, while others use the Set-Cookie field values. I therefore wrote a "cookie splitter" to create separate headers, which is being reviewed.

**Comment by tomball** [comment] 2017-04-24 21:02
Fixed in current source.

**Closed by tomball** 2017-04-24 21:02 UTC
