### ISSUE TITLE
No constructor for annotations with CLASS retention

### ISSUE THREAD

**Issue by tux-mind** [google/j2objc#1008] opened 2018-10-19 14:19 UTC
In translating [JsonSubTypes.java](https://github.com/FasterXML/jackson-annotations/blob/jackson-annotations-2.8.11/src/main/java/com/fasterxml/jackson/annotation/JsonSubTypes.java) no constructor for the inner annotation is created ( `JsonSubTypes.Type` ).

When other classes try to use the annotation, a compilation error occurs as the `create_ComFasterxmlJacksonAnnotationJsonSubTypes_Type` function does not exist.

Tested with j2objc 2.0.4.1 and 2.2.

**Comment by tomball** [comment] 2018-10-22 16:49
The issue is that the inner annotation type doesn't have runtime retention. Currently we only generate support for runtime retention, but need to also generate types with class retention (which has to be down without changing what types are returned by reflection).

**Comment by tomball** [comment] 2018-10-22 16:50
Temporary workaround is to add a "@Retention(RUNTIME)" annotation to the inner type.

**Comment by antonio-cortes-perez** [comment] 2018-11-27 21:29
Fixed in version 2.3.

**Closed by antonio-cortes-perez** 2018-11-27 21:29 UTC
