### ISSUE TITLE
Can't MAKE/Built project anymore with Clang 13.1.6 -> unused-but-set-variables in several generated .M files

### ISSUE THREAD

**Issue by herbertvuijk** [google/j2objc#1883] opened 2022-05-16 11:04 UTC
I used to be able to MAKE J2Objc without troubles. Today I wanted to make the project again to export a different architecture

I guess my Clang compiler updated with some OSX/XCode updates because it doesn't want to compile a bunch of files anymore. For example DecimalFormat.m (java/text) failes on an unused-but-set variable. There are more files failing with the same error.

I think this is related to a Clang 13 change, see here similar complaints: https://github.com/ClickHouse/ClickHouse/issues/27705

> building jre_emul archs: iphone
> (..)
> /Users/herbert/Documents/GitHub/j2objchvu/jre_emul/build_result/Classes/java/text/DecimalFormat.m:3006:8: error: variable 'phaseOneStart' set but not used [-Werror,-Wunused-but-set-variable]

How to get clang to ignore these warnings instead of breaking on it? 

I tried to add some Clang options in the MAKE file but it didnt help:
FAT_LIB_COMPILE = $(CLANG) **-Wno-everything -Wno-unused-variable -Wno-unsused-but-set-variable** $(OBJCFLAGS) -I$(GEN_OBJC_DIR)

Any ideas? Thanks!

Nb: I tried this from the latest revision mainline as well as the 2.8 tag, both giving the same issue

**Comment by herbertvuijk** [comment] 2022-05-16 11:49
Fixed it finally. Had to add the flags on 3 places in different MAKE files and now it runs again.
<img width="940" alt="Schermafbeelding 2022-05-16 om 13 48 14" src="https://user-images.githubusercontent.com/8804409/168586248-dc21e549-9d0e-4dcb-a05d-225c258456d1.png">
<img width="945" alt="Schermafbeelding 2022-05-16 om 13 48 21" src="https://user-images.githubusercontent.com/8804409/168586257-ce71b589-33cc-48ec-97d0-7c52c587e647.png">

**Comment by tomball** [comment] 2022-05-16 17:03
Duplicate of issue #1872.

**Closed by tomball** 2022-05-16 17:03 UTC
Labels: duplicate
