### ISSUE TITLE
Multiple classes in one Java file causing issues.

### ISSUE THREAD

**Issue by ScottPierce** [google/j2objc#674] opened 2015-12-07 19:59 UTC
[Sources](https://github.com/google/j2objc/files/54471/rxjava-1.1.0-sources.zip)
[ObjC Transpiled Sources](https://github.com/google/j2objc/files/54470/rxjava-j2objc.zip)

I'm seeing what I believe to be a bug. Included above are the sources to reproduce.
1. I'm using the command `j2objc -use-arc --doc-comments -d ./out ./rxjava-1.1.0-sources.jar` to get the above transpiled sources.
2. I'm then using the command to compile the transpiled sources:
   `j2objcc -g -ObjC -fobjc-arc -I./out `find ./out/*``
3. I get the following errors:

```
./out/rx/internal/util/unsafe/MpscLinkedQueue.m:10:10: fatal error: 
      'rx/internal/util/unsafe/BaseLinkedQueueConsumerNodeRef.h' file not found
#include "rx/internal/util/unsafe/BaseLinkedQueueConsumerNodeRef.h"
         ^
1 error generated.
./out/rx/internal/util/unsafe/SpscLinkedQueue.m:11:10: fatal error: 
      'rx/internal/util/unsafe/BaseLinkedQueueConsumerNodeRef.h' file not found
#include "rx/internal/util/unsafe/BaseLinkedQueueConsumerNodeRef.h"
         ^
1 error generated.
```

I diagnosed the first error: When examining the java source you can see that `MpscLinkedQueue` extends the abstract class `BaseLinkedQueue`, which extends the abstract class `BaseLinkedQueueConsumerNodeRef`.

Both `BaseLinkedQueue` and the `BaseLinkedQueueConsumerNodeRef` seem to be classes in the BaseLinkedQueue.java file, but aren't inner classes. j2ObjC seems to be handling this incorrectly and not generating a file for the class, or if it is generating the class, it's looking for it in the wrong place.

**Comment by tomball** [comment] 2015-12-09 00:24
The problem is that those other files are referencing a non-public class in another source file that doesn't have the same name as the class (public classes are required to, but non-public aren't). It's lousy coding style, but legal Java.

We'll have to think about the best way to address this. Java compilers don't care, because they generate class files that aren't that associated with the source file (other than a SourceFile attribute). j2objc keeps all class declarations in the same .h/.m files so build systems can find them (most check file suffixes). The source file isn't available from the type bindings we get from the Eclipse JDT, but maybe if the original source file on the source path we can track it down.

As a workaround, you can move the referenced class (BaseLinkedQueueConsumerNodeRef, in this case) into a Java source file with the same name. Bonus points for getting a pull request to fix that accepted by the RxJava folks!

**Comment by spierce7** [comment] 2015-12-09 07:20
@tomball Thanks for your response and analysis. I was able to get it working by modifying the source and splitting up everything into multiple files.

**Comment by th3hamm0r** [comment] 2017-03-16 15:37
I stumbled over the same issue, so thank you both for the question and the response :+1:

@tomball Are there any updates on this on the j2objc-side? I'm using version 1.2 at the moment, so is it possible that this is fixed in 1.3 or higher?

**Comment by tomball** [comment] 2017-03-16 20:16
We haven't found any workable solution. Java tools like Gradle and Maven avoid the unknown-number-of-classes-per-source issue blocking on all Java compilation for a library before starting dependent steps.

However, tools like Xcode and [Bazel](https://bazel.build/) want to be able to determine all build artifacts before running, rather than discover bonus artifacts as they're running (that's why [our Xcode rule defines ${INPUT_FILE_BASE}.h and ${INPUT_FILE_BASE}.m outputs](http://j2objc.org/images/xcode-build-rules.png)).  In Bazel's case, requiring a determinant build graph improves its cache opportunities significantly, resulting in shorter and more accurate builds.

In theory we could fix this issue by emitting additional header files for each package-private type in a shared source file, but that doesn't work because of build tool requirements. If you or anyone else has a better suggestion that will work with determinate build tools, we'd love to hear your ideas!

**Comment by antonio-cortes-perez** [comment] 2019-11-04 18:32
Looks like this issue is fixed. I tried the steps in the first comment with j2objc-2.5 and I was able to compile the transpiled source. I also inspected MpscLinkedQueue.m and the only includes are:

#include "J2ObjC_source.h"
#include "java/lang/NullPointerException.h"
#include "rx/internal/util/atomic/LinkedQueueNode.h"
#include "rx/internal/util/unsafe/BaseLinkedQueue.h"
#include "rx/internal/util/unsafe/MpscLinkedQueue.h"
#include "rx/internal/util/unsafe/UnsafeAccess.h"
#include "sun/misc/Unsafe.h"

**Closed by antonio-cortes-perez** 2019-11-04 18:32 UTC
