### ISSUE TITLE
URL class fails loading file URLStreamHandler

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#912] opened 2017-11-22 15:51 UTC
Hi,

we just moving our project to j2objc 2.x. Seems everything works, excepting URL classes. Code like this:

File imageDirectory = URL("file://path/to/file");

throws exeption runtime:

Terminating app due to uncaught exception 'JavaLangAssertionError', reason: 'java.lang.AssertionError: java.lang.ClassNotFoundException: sun.net.www.protocol.file.Handler'

It worked without problems in j2objc 1.x. Any idea how to solve?

**Comment by tomball** [comment] 2017-11-22 18:55
j2objc 2.x includes newer Android libcore classes, as the Oreo release is mostly based on OpenJDK files rather than Apache Harmony. That's good for improved compatibility with the JRE, but you found a regression where the old version statically linked in the file protocol handler, while OpenJDK dynamically loads it. Because it is only dynamic loaded, the linker didn't include sun.net.www.protocol.file.Handler. 

I should be able to deliver a source fix for that next week, assuming reviewers are back from vacation. There are two workarounds you can use today:

- Specify the -ObjC flag when linking. This tells the loader to include all classes in the JRE emulation library (including the file handler), so the increased app size might be an issue.
- Add a static reference to the file handler class somewhere in your code. All that's needed is something like `private static final Class<?> unusedHandler = sun.net.www.protocol.file.Handler.class;`. This will force the linker to include the file, and can be done in shared code since it will have no effect on Android or with a JVM.

**Comment by tomball** [comment] 2017-12-02 17:40
Fixed in current source.

**Closed by tomball** 2017-12-02 17:40 UTC
