### ISSUE TITLE
2x WeakHashMap references prevent object deallocation

### ISSUE THREAD

**Issue by andrewebling** [google/j2objc#430] opened 2014-11-04 16:20 UTC
Summary: an object referenced by two WeakHashMaps does not get deallocated when all other references to it have gone.

Consider the following Java code:

```Java
        WeakHashMap<MyObj, Boolean> weakHashMap = new WeakHashMap<MyObj, Boolean>();
        WeakHashMap<MyObj, Boolean> weakHashMap2 = new WeakHashMap<MyObj, Boolean>();

        MyObj o = new MyObj();
        weakHashMap.put(o, true);
        weakHashMap2.put(o, true);

        o = null;
```

…when translated with J2ObjC:

```Objective-c

    JavaUtilWeakHashMap *weakHashMap = [[JavaUtilWeakHashMap alloc] init];
    JavaUtilWeakHashMap *weakHashMap2 = [[JavaUtilWeakHashMap alloc] init];
    ComCompanyMain_MyObj *o = [[ComCompanyMain_MyObj alloc] init];
    (void) [weakHashMap putWithId:o withId:[JavaLangBoolean valueOfWithBoolean:YES]];
    (void) [weakHashMap2 putWithId:o withId:[JavaLangBoolean valueOfWithBoolean:YES]];
    o = nil;
```

…and if a `dealloc` method is added to the translated versions of `MyObj`, which simply logs “MyObj dealloc”, it becomes clear that the instance of `MyObj` never gets deallocated after the above code has run.

However, if `weakHashMap2` is never initialised, or the instance of `MyObj` is never added to it (i.e. there is only a reference in a single `WeakHashMap`), the instance of `MyObj` gets deallocated as expected.

So it seems the deallocation of the `MyObj` instance gets blocked by two separate weak references held in separate `WeakHashHap`s.

Expected results: I would expect the instance of `MyObj` still get deallocated, even when referenced from two separate `WeakHashMap`s, when all other references are gone.

**Comment by nbransby** [comment] 2015-02-02 10:16
@tomball presuming this is still the case 0.9.6?

**Comment by tomball** [comment] 2015-02-02 15:07
Yes, we're still slowly working through the issues list. :(

**Comment by nbransby** [comment] 2015-05-15 13:09
Still no joy?

**Comment by tomball** [comment] 2015-05-15 13:57
[Too many plates](https://www.youtube.com/watch?v=FK4nh5I0jpE&list=RDFK4nh5I0jpE&index=1)

**Comment by nbransby** [comment] 2015-08-05 15:54
Ok 9 months after reporting, any chance you could serve up this plate soon? Major cause of memory leaks for us

**Comment by tomball** [comment] 2015-08-10 18:52
WeakHashMap use normally is restricted to just a few use cases, but are
very frequently incorrectly used as object caches
<http://stackoverflow.com/questions/1802809/javas-weakhashmap-and-caching-why-is-it-referencing-the-keys-not-the-values>.
If your app needs a real cache class, I strongly recommend replacing
WeakHashMap with something like Guava's cache support
<https://code.google.com/p/guava-libraries/wiki/CachesExplained>.

This issue still needs to be fixed, but fixing it may not address some
critical app issues.

**Comment by nbransby** [comment] 2015-08-10 19:21
Yes don't worry, we are using it correctly :) I can refresh my memory and let you know our use case if you are interested

We are also already using Guava caches for caching,  with weakValues as it goes. I'm guessing that this issue affects this also although we haven't created a specific test case for that too

**Comment by kstanger** [comment] 2015-09-11 20:32
I've been looking into this issue. The problem is that our ReferenceQueue is holding strong references to the referent object and doesn't release the object for deallocation until it is removed from the queue. This differs from Java behavior where the referent can be finalized and deallocated any time after being added to the queue.

I may have a fix on the way.

**Comment by kstanger** [comment] 2015-09-15 14:53
Fixed in latest source.

**Closed by kstanger** 2015-09-15 14:53 UTC
