### ISSUE TITLE
Parse XML with SAXParser andDefaultHandler the method endElement no name value

### ISSUE THREAD

**Issue by SimonZhangXi** [google/j2objc#876] opened 2017-08-26 08:11 UTC
Parse XML with javax.xml.parsers.SAXParser and org.xml.sax.helpers.DefaultHandler,the interface method endElement argment "name" no vlaue.
`public void endElement(String uri, String local, String name) {
    /**
    /* In the IOS argment name always is nil/null.
   */
}`

**Comment by zhouyanggao** [comment] 2017-08-28 14:15
Do you have a simple example that we can use to reproduce this issue?

**Comment by tomball** [comment] 2017-08-28 14:25
Is the behavior different that on Android? If so, what version of Android are you testing with?

**Comment by tomball** [comment] 2017-09-06 04:14
The attached zip file demonstrates the issue, where endElement's name parameter is an empty string. Since the XML parser support classes are not updated to Android N, I'll update them and see if that fixes the issue (if not, then fix it).

[ParseXML.zip](https://github.com/google/j2objc/files/1279732/ParseXML.zip)

**Comment by tomball** [comment] 2017-09-13 17:41
Fixed in current source.

**Closed by tomball** 2017-09-13 17:41 UTC

**Comment by tomball** [comment] 2017-09-13 17:42
Please note: this bug may still be present in Android, prior to the Nougat release. That's the source j2objc's jre_emul library used. The SAX2 driver was replaced in Nougat, which we're porting to j2objc.

**Comment by SimonZhangXi** [comment] 2017-09-14 11:00
My code running fine at Android and Java 7 . This bug find at IOS10. I am Chinese Sorry about English.

**Comment by tomball** [comment] 2017-09-14 17:27
I'm glad that code works for you on Android. 

不用担心书面语言差异，我们和世界各地的同事一起生活和工作。翻译成我不知道的语言时使用的一个技巧是使用Google翻译，然后复制输出并重新翻译成英文 - 如果翻译翻译很难阅读，则我编辑原始文本并尝试再次。这应该与中文 - >英文 - >中文一样工作，虽然显然我无法验证它是否有效。
