### ISSUE TITLE
@Property annotation doesn't use Java setter

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#956] opened 2018-03-11 16:56 UTC
In simple class:

```java
import com.google.j2objc.annotations.Property;

public class Test {
    @Property private int x;

    public void setX(int x) {
        this.x = x;
    }

    public int getX() {
        return x;
    }
}
```

is generated *.h with property declaration, but without setter:

```objc
...
@property (nonatomic, getter=getX) jint x;
...
```

I looked into j2objc code and it looks like that setters should be used in generated property declaration as well. I even tried to set them manually through @Property annotation (`@Property("setter=setXWithInt:") private int x;`), but then j2objc shows warning: 

`Test.java:4: Non-existent setter specified: setXWithInt:`

even when this method exists in generated code. Any idea, how to use `@Property` annotation correctly?

**Comment by tomball** [comment] 2018-03-12 04:53
It's a bug, I should have a fix pushed mid-week. The issue is that the setter's name isn't correctly mangled to match the generated code. 

When this is fixed, the setter name should be its name in the Java source (not mangled), so "setter=setX".

**Comment by tomball** [comment] 2018-03-13 17:10
Fixed in current source.

**Closed by tomball** 2018-03-13 17:10 UTC

**Comment by tomball** [comment] 2018-03-13 19:42
Fixed in current source.
