### ISSUE TITLE
NSPredicate "class == %@" does not work after linking JRE

### ISSUE THREAD

**Issue by ifabijanovic** [google/j2objc#806] opened 2016-10-13 08:35 UTC
Hello,

I encountered a strange issue after linking some j2objc code to my project. It seems that after linking JRE the type predicate stops working:

`[NSPredicate predicateWithFormat:@"class == %@", [SomeType class]]`

I am attaching a small Xcode project which demonstrates this problem. Is some code in JRE swizzling `className` or something? This is kind of worrying as it makes me wonder will some other parts of the standard library stop working after linking Java libraries.

[PredicateError.zip](https://github.com/google/j2objc/files/526572/PredicateError.zip)

**Comment by kstanger** [comment] 2016-10-13 18:42
This is a duplicate of #785

**Closed by kstanger** 2016-10-13 18:42 UTC

**Comment by tomball** [comment] 2016-10-13 18:45
You can try https://github.com/google/j2objc/pull/787 as a temporary workaround, though we'll be enhancing that work before committing it to the main project.
