### ISSUE TITLE
Parameter --no-package-directories generates directories into #include

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1956] opened 2022-11-09 15:53 UTC
I updated j2objc on our project to latest main branch. It looks like that `--no-package-directories` parameter is not working correctly.

Older version:
- it generated all files into one folder
- the `#includes` were without paths

New version (main branch):
- it is generating all files into one folder (same as before)
- the `#includes` ARE with paths (not as before)

Example with 2 simple classes

```java
package com.tappytaps;

public class Test {
    public void test() {
        System.out.println("Hallo from the Test class");
    }
}
```
and 
```java
package com.tappytaps;

public class Test2 {
    public void test2() {
        Test test = new Test();
        test.test();
    }
}
```

I generated objective-c code using:
```bash
j2objc com/tappytaps/Test.java com/tappytaps/Test2.java  --no-package-directories
```

The beginning of  generated Test2.m now have:
```objective-c
#include "J2ObjC_source.h"
#include "Test2.h"
#include "com/tappytaps/Test.h" // <<< this is IMHO bug

#if __has_feature(objc_arc)
#error "Test2 must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComTappytapsTest2
```

Here is output from older version of j2objc:
```objective-c
#include "J2ObjC_source.h"
#include "Test.h"
#include "Test2.h" // <<< this is IMHO corrrect

#if __has_feature(objc_arc)
#error "Test2 must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComTappytapsTest2
```

Example project:
[testProject.zip](https://github.com/google/j2objc/files/9972849/testProject.zip)

**Comment by thieren** [comment] 2022-11-12 14:30
I've identified the cause of this to be the commit https://github.com/google/j2objc/commit/6bb630a9a5eecfecfccc538034b63e2be9809e13

Since I don't know the background of this change I didn't open a pull request to revert this, but if you need a quick fix you can download a fork with a fix [here](https://github.com/thieren/j2objc) until it is resolved in this repo.

**Comment by tomball** [comment] 2022-11-12 15:45
Thanks for the investigation! The background was that a checker-framework source jar was missing the source for a nullability annotation, and since multiple packages have an annotation with that name, it took some time to determine *which* package had the problem since the error message didn't include the package. This change was intended to improve the error message, but also broke the `--no-package-directories` flag.

Thanks also for the pull request offer, but it's easier to rollback the bad commit internally ([pull request](https://github.com/google/j2objc/pull/1961)). I should get this code-reviewed and committed Monday.

**Closed** 2022-11-14 20:52 UTC
