### ISSUE TITLE
"building for iOS simulator, but linking in object file built for OSX, for architecture x86_64"

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#611] opened 2015-09-11 16:02 UTC
After upgrading to Xcode 7, linker stops to link library from distribution when building for simulator.

**Comment by ex3ndr** [comment] 2015-09-13 13:53
Sorry, but this is very urgent thing as everybody started to switch to xcode 7 after release couple days ago.

**Comment by tomball** [comment] 2015-09-13 23:10
What library? If it's one included in j2objc's distribution, you have the option of building from source, then using the arch-specific libraries in the library's build_result directory. If the issue is with jre_emul, for example, link with jre_emul/build_result/simulator-libjre_emul.a. 

Another option is to add the jre_emul/JreEmulation.xcodeproj as a subproject, and link with it instead of using a "-l jre_emul" flag.

**Comment by tomball** [comment] 2015-09-13 23:11
The reason this and your other bug report are currently marked "cannot reproduce" but are still open is because you reported general bugs without enough information to reproduce them.

**Comment by ex3ndr** [comment] 2015-09-14 16:37
Yes, problems is with jre_emul library.

**Comment by tomball** [comment] 2015-09-14 21:28
The problem is that Xcode no longer accepts use of an OS X library for 64-bit simulator models, like iPhone 6 -- even though the code itself is identical. We cannot distribute a single library any more that supports all architectures, because lipo won't accept both OS X x86_64 and an iOS x86_64 builds in the same fat library. We therefore need to change the build so the OS X and iOS archs are in different fat libraries.

One workaround is to use use 32-bit simulator test, like iPhone 4S, until there is a rebuilt release. Another is to add jre_emul/JreEmulation.xcodeproj as a sub-project.

**Comment by ex3ndr** [comment] 2015-09-17 19:21
i make rebuilded version of j2objc 0.9.8.1 and removed OSX support and changed arch type for simulator and prepared truncated package (guava doesn't respect some parameters as jre_emul do).
If anyone is interested in this, they can grab it at link: https://dl.bintray.com/actor/j2objc/j2objc-0.9.8.1.zip

**Comment by tomball** [comment] 2015-09-18 17:09
Fixed in current source.

**Closed by tomball** 2015-09-18 17:09 UTC

**Comment by tomball** [comment] 2015-09-18 17:30
Thanks for working on this, but issue 611 has been fixed by updating our
build.

**Comment by zipeldiablo** [comment] 2015-09-23 12:00
You saved my day, thanks guys

**Comment by davidmoore1** [comment] 2015-09-25 15:32
Is this fix compatible with both XCode 6 and XCode 7?  Also is there any plan to make an official release like a 0.9.8.2 that would contain this fix anytime soon?

**Comment by tomball** [comment] 2015-09-25 18:11
Yes, and released: https://github.com/google/j2objc/releases/tag/0.9.8.2

**Comment by gagoongx2** [comment] 2015-09-30 02:54
linke error in Xcode 7
(linker command failed with exit code 1)

Solution is below
not include mac x86_64 library in universal 
# cp -r platform/x86_64-mac/lib/* lib

Plus
If you want to build with libstdc++.
change compiler clang to gcc , g++

+ #CC=clang
+ #CXX=clang
+ CC=gcc
+ CXX=g++

++#STDLIB=libc++
++STDLIB=libstdc++

**Comment by tomball** [comment] 2015-09-30 03:13
Solution is to use the latest release (0.9.8.2.1) or latest source code, as
this issue was closed when it was fixed.

**Comment by ex3ndr** [comment] 2015-10-08 06:16
Worked for me
